name: PR Docker Cleanup

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  cleanup_pr_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up PR images
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const isMerged = context.payload.pull_request.merged;
            
            console.log(`PR #${prNumber} was ${isMerged ? 'merged' : 'closed without merging'}`);
            
            // Get all package versions
            const { data: versions } = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
              package_type: 'container',
              package_name: repo,
              org: owner,
              per_page: 100
            });
            
            // Filter versions that match this PR pattern
            const prVersions = versions.filter(version => 
              version.metadata.container.tags.some(tag => tag.startsWith(`pr-${prNumber}-`))
            );
            
            if (prVersions.length === 0) {
              console.log(`No images found for PR #${prNumber}`);
              return;
            }
            
            // Delete matching versions
            for (const version of prVersions) {
              console.log(`Deleting version ${version.id} with tags: ${version.metadata.container.tags.join(', ')}`);
              await github.rest.packages.deletePackageVersionForOrg({
                package_type: 'container',
                package_name: repo,
                org: owner,
                package_version_id: version.id
              });
            }
            
            console.log(`Successfully cleaned up ${prVersions.length} PR images`);
